import cloud.shareApp.User;
import org.apache.avro.file.DataFileWriter;
import org.apache.avro.specific.SpecificDatumWriter;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;
import java.io.IOException;

/**
 * code generation: compile avro schema file to avro class
 * serialize an avro class generated by maven avro plugin
 */
public class AvroSerializerWithGeneratedCode {
    private static final Logger logger= LoggerFactory.getLogger(AvroSerializerWithGeneratedCode.class);
    public static void main(String[] args) {
        logger.info("serializing avro object!");
        User user = User.newBuilder()
                .setName("sadeq")
                .setFavouriteNumber(7)
                .build();
        SpecificDatumWriter<User> userSpecificDatumWriter = new SpecificDatumWriter<>(User.class);
        try(DataFileWriter<User> userDataFileWriter = new DataFileWriter<>(userSpecificDatumWriter)){
        userDataFileWriter.create(user.getSchema(),new File("user.avro"));
        userDataFileWriter.append(user);
        }catch (IOException e){
            logger.error("avro file writing failed!",e);
        }
    }
}
